import "bootstrap/dist/css/bootstrap.min.css";
import "./sass/main.scss";
import "./header";
import "./navigate";
import "./breadcrumbs";
import "./card.js";
import "./filterSort";
import "./pageText";
import "./images";
